# This is the test workflow that will run the test.sh script

name: test
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: metasploit reverse shell
      run: sh ./test.sh
